### ISSUE TITLE
Documentation of configuration is wrong

### ISSUE THREAD

**Issue by thomasstreckercc** [jacob-meacham/grunt-lcov-merge#1]
The documentation states that the lcovMerge should be configured as follows:

``` javascript
lcovMerge: {
  options: {
    emitters: ['event', 'file'],
    outputFile: 'mergeLcov.info'
  },
  files: ['build/coverage/*.info', 'build/coverage/**/*.info']
}
```

This leads to an error, however. The following works:

``` javascript
lcovMerge: {
  options: {
    emitters: ['event', 'file'],
    outputFile: 'mergeLcov.info'
  },
  files: {
    src: ['build/coverage/*.info', 'build/coverage/**/*.info']
  }
}
```

So either the documentation or the configuration should be updated.

**Comment by jacob-meacham** [comment]
Thanks for reporting, I'll take a look and see whats up! Using files: [...] works for me, so I'll try to get a repro of your issue.

**Comment by thomasstreckercc** [comment]
Maybe it's version-specific? We're using Node v0.12.0, NPM v2.5.1 and Grunt v0.4.5.
When using the configuration as documented I receive the following error message:

```
Running "lcovMerge:lcovMerge" (lcovMerge) task
Warning: Cannot use 'in' operator to search for 'src' in generated/reports/coverage/**/*.info Use --force to continue.
Aborted due to warnings.
```

This in turn pointed me to try the other version, as suggested here: https://github.com/gruntjs/grunt-contrib-jshint/issues/37

**Comment by jacob-meacham** [comment]
Does using just src:[...] work for you? I'm having trouble reproducing here, but I'll gladly update the docs. For reference, all of

files: [...]
files {
   src: [...]
}
src: [...]

work for me.

**Comment by jacob-meacham** [comment]
PR here: https://github.com/jacob-meacham/grunt-lcov-merge/pull/2

**Comment by jacob-meacham** [comment]
Just release 0.1.3 with the docs change. Thanks!
